theme = "hyde"
baseURL = "https://stillanixrookie.github.io/"
languageCode = "en-us"
title = "Gavin Vales"

[params]
	description = "My website, built with Hugo, hosted by Github."

[Menus]
	main = [
		{Name = "Github", URL = "https://github.com/StillANixRookie/"},
		{Name = "gvales2831997@gmail.com", URL = "gvales2831997@gmail.com"},
	]
